### ISSUE TITLE
glitch in profile for processing exemption

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#20] opened 2020-07-21 21:11 UTC
Another glitchy thing going on here:

1) the profile information duplicates on the same page
2) the building exempt status is not showing up in the building profile. I tried going back to the dashboard and hitting refresh. I tried closing out of the system and reopening the PEPR Shaker and I can't seem to get it to take. 

![image](https://user-images.githubusercontent.com/68078441/88107394-df7a0600-cb5b-11ea-95f3-cdf333604b43.png)

**Comment by derekwmiller** [comment] 2020-07-23 01:01
Wendy had a similar issue several weeks ago. It was a busted server request that caused a page error and prevented execution.

I think, in this case, it was the same server error that caused #13 ... since that has been resolved I cannot reproduce this behavior. So - I'm going to close this. If it continues to happen, reopen this issue or create a new one.

**Closed by derekwmiller** 2020-07-23 01:01 UTC
