### ISSUE TITLE
2nd building search yields previously searched building profile

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#12] opened 2020-07-16 18:49 UTC
I'm running into a glitchy issue as follows:

I search for one building and view its profile. Then I go to the Building tab to search for the next building. The search function returns the new building I entered. However, when I click on it, it actually goes to the profile for the previously searched building. Using the “Clear” button doesn’t resolve this. I have to click on "Dashboard" and then refresh that page each time I search for a new building to prevent this from happening.

**Comment by LisaTimmerman** [comment] 2020-07-21 20:48
This seems to be happening with the Exemption Track-It page too. When I'm going into review and improve an exemption, after it's approved, I try to go back to the Exemption queue menu. The next building I try to open yields the data for the previous building I was working on. This only gets resolved by going back to the Dashboard, refreshing the page, then going back into the Exemption Track-It queue.

**Comment by derekwmiller** [comment] 2020-07-22 20:26
interesting. i will look into this

**Comment by derekwmiller** [comment] 2020-07-23 01:00
Wendy had a similar issue several weeks ago. It was a busted server request that caused a page error and prevented execution. 

I think, in this case, it was the same server error that caused #13 ... since that has been resolved I cannot reproduce this behavior. So - I'm going to close this. If it continues to happen, reopen this issue or create a new one.

**Closed by derekwmiller** 2020-07-23 01:00 UTC
